security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email 

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Authentification par formulaire
            form_login:
                login_path: app_login     
                check_path: app_login     
                default_target_path: app_home 
            
            # Déconnexion : définit la route de déconnexion
            logout:
                path: app_logout  
                target: app_home
            security: true

    # Contrôle d'accès : définis ici qui a accès à quelles routes
    access_control:
        - { path: ^/profile, roles: ROLE_USER }
        - {path: ^/admin, roles: ROLE_ADMIN }

        - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    # Configurations spécifiques aux tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3 
                memory_cost: 10 

